services:
  rims-mcp:
    container_name: rims-mcp
    build: .
    environment:
      - API_ENDPOINT=${API_ENDPOINT}
      - WEB_PAGE_URL=${WEB_PAGE_URL}
      - COMPETITION_ID=${COMPETITION_ID}
    volumes:
      - ./:/app
    stdin_open: true
    tty: true